language: go

go:
  - 1.7.x
  - master
  
script: 
  - pwd
  - go install ...
  - cd $GOPATH
  - ls -lahtr ./bin/
  - go test -v ./src/github.com/RidiculousRichard/sandbox
  - '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN'
  - ./bin/sandbox
